version: "3.8"

services:
  db:
    image: postgres:16
    container_name: odoo_db1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data1:/var/lib/postgresql/data

  odoo17:
    image: odoo:17.0
    container_name: odoo_app1
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data1:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    command: >
      odoo -d odoo_db1
      -u gestion_projets_etudiants
      --dev=xml
      --db_user=odoo
      --db_password=odoo
      --db_host=db

volumes:
  odoo-web-data1:
  odoo-db-data1: